### ISSUE TITLE
UploadWithUploadToken not working

### ISSUE THREAD

**Issue by autowp** [apivideo/go-api-client#15]
UploadWithUploadToken not working because of upload token is not sent with query string. (parameter `token` of `UploadWithUploadTokenWithContext` is not used)

https://github.com/apivideo/go-api-client/blob/main/api_videos.go#L842

**Comment by autowp** [comment]
Not sure but maybe something like that is proper fix https://github.com/apivideo/go-api-client/pull/16

**Comment by olivierapivideo** [comment]
Thanks for your PR. As this client is generated we can't merge PR that are made directly here.
I've fixed your issue in #17.
Thanks for you report & PR, and sorry for the inconvenience.
